SENSOR_COLS = ["sig_a1", "sig_a2", "sig_a3", "sig_b1", "sig_b2", "sig_b3"]

[SUBSYSTEM_MAP]
a = ["sig_a1", "sig_a2", "sig_a3"]
b = ["sig_b1", "sig_b2", "sig_b3"]


[VANILLA_TCN_VAE_CHANNEL_DIMENSIONS]
enc_tcn1_in_dims = [9999, 60, 40, 30, 20]
enc_tcn1_out_dims = [60, 40, 30, 20, 10]
enc_tcn2_in_dims = [10, 10, 8, 5, 3]
enc_tcn2_out_dims = [10, 8, 5, 3, 1]
dec_tcn1_in_dims = [1, 3, 5, 8, 10]
dec_tcn1_out_dims = [3, 5, 8, 10, 10]
dec_tcn2_in_dims = [10, 20, 30, 40, 60]
dec_tcn2_out_dims = [20, 30, 40, 60, 9999]

[MULTI_LATENT_TCN_VAE_CHANNEL_DIMENSIONS]
enc_tcn1_in_dims=[9999, 25, 15, 10, 6]
enc_tcn1_out_dims=[25, 15, 10, 6, 5]
enc_tcn2_in_dims=[5, 5, 5, 4, 3]
enc_tcn2_out_dims=[5, 5, 4, 3, 1]
dec_tcn1_in_dims=[1, 3, 4, 5, 5]
dec_tcn1_out_dims=[3, 4, 5, 5, 6]
dec_tcn2_in_dims=[6, 7, 10, 15, 25]
dec_tcn2_out_dims=[7, 10, 15, 25, 9999]

[COMBINED_UNIVARIATE_TCN_VAE_CHANNEL_DIMENSIONS]
enc_tcn1_in_dims=[99, 2, 3, 5, 5]
enc_tcn1_out_dims=[2, 3, 5, 5, 5]
enc_tcn2_in_dims=[5, 4, 4, 3, 2]
enc_tcn2_out_dims=[4, 4, 3, 2, 1]
dec_tcn1_in_dims=[1, 3, 4, 5, 5]
dec_tcn1_out_dims=[3, 4, 5, 5, 5]
dec_tcn2_in_dims=[5, 5, 5, 3, 2]
dec_tcn2_out_dims=[5, 5, 3, 2, 9999]
